@api = http://localhost:3020/api/v1/prod-serv
#@api = http://187.229.22.99:8010/api/v1/prod-serv

### GET
get {{api}}/
### GET
GET {{api}}/producto/9001-000000000001
### GET ITEM
GET {{api}}/presentacion/9001-000000000001
### GET ITEM
GET {{api}}/102?keyType=OK
### GET ITEM
GET {{api}}/102?keyType=BK
##Buscar por descripcion 
GET {{api}}/101?keyType=BK
### GET POR DESCRIPCION
GET {{api}}/search?q=REFRIGERADOR HORIZONTAL 250L 1PTA
### GET POR ARTICULOS ACTIVOS ACTIVO 
GET {{api}}/activos
### GET POR ESTATUS
GET {{api}}/estatus/VIGENTE
### GET POR NEGOCIO QUE LO VENDE
GET {{api}}/negocio/9001-TODOS
### GET POR PRESENTACION
GET {{api}}/presentacion/descripcion/Empresarial Gris Oxford - 500GB - 32RAM
### GET ESTADISTICAS
GET {{api}}/estadisticas


//--------------------Presentaciones
### get
GET {{api}}/presentacion/9003-000000000003
### GET
get {{api}}/presentacion/9001/info/9004-000000000004-000000001
### GET
get {{api}}/presentacion/9003-000000000003/paquete/9003-000000000003-000000001
### GET
get {{api}}/presentacion/9003-000000000003/archivos/9003-000000000003-000000001
### GET

### POST PAQUETE




router.delete('/paquete/:id/presentacion/:idPresentacion/:paqueteId', prodServController.deleteProdServPaquete);
### POST PRESENTACION
delete {{api}}/paquete/9001-000000000001/presentacion/9001-000000000001-000000003/999999999999999999999
Content-Type: application/json

{
      "_id": false,
      "IdArchivoOK": "213213213",
      "IdArchivoBK": "654321",
      "DesArchivo": "Manual del tonto",
      "RutaArchivo": "/archivos/manuales/usuario.pdf",
      "IdTipoArchivoOK": "PDF",
      "Archivo": "usuario.pdf",
      "IdTipoSeccionOK": "A2",
      "Secuencia": 1,
      "Principal": "S",
      "detail_row": {
        "Activo": "S",
        "Borrado": "N",
        "detail_row_reg": [
          {
            "_id": false,
            "FechaReg": "2024-11-16T12:34:56Z",
            "UsuarioReg": "admin"
          }
        ]
      }
    }



### PUT PRESENTACION
PUT {{api}}/presentacion/9001-000000000001/9001-000000000001-000000001
Content-Type: application/json

{
  "IdPresentaOK": "new-isadsadd",
  "IdPresentaBK": "new-id-bk",
  "CodigoBarras": "new-HOLA",
  "DesPresenta": "Nueva Presentación",
  "Indice": "001",
  "Principal": "S",
  "estatus": [
    {
      "IdTipoEstatusOK": "1",
      "Actual": "S",
      "Observacion": "Presentación activa"
    }
  ],
  "info_vta": [],
  "info_ad": [],
  "paquete": [],
  "archivos": []
}

### DELETE
delete {{api}}/presentacion/9001-000000000001/new-isadsadd



//-------------------- FIN Presentaciones














### POST ITEM PRODUCTO
POST {{api}}
Content-Type: application/json

{ 
    "IdProdServPK" : 101, 
    "IdProdServOK" : "101", 
    "IdProdServBK" : "REFR101", 
    "IdProdServMaOK" : "2", 
    "IdProdServMaBK" : "2", 
    "DesProdServ" : "REFRIGERADOR HORIZONTAL 250L 1PTA", 
    "IdUMedidaOK" : "2", 
    "IdUMedidaBK" : "2", 
    "cat_prod_serv_estatus" : [
        {
            "IdTipoGenEstatusOK" : "5", 
            "IdGenEstatusOK" : "24", 
            "TipoEstatus" : "NO DISPONIBLE", 
            "Actual" : "S", 
            "Observacion" : "Fuera de stock", 
            "detail_row" : {
                "FechaReg" : "2023-06-15T08:45:22+07:00", 
                "UsuarioReg" : "JSMITH"
            }
        }
    ], 
    "cat_prod_serv_paquetes" : [
        {
            "IdProdServOK" : "2", 
            "IdProdServBK" : "2", 
            "DesProdServ" : "REFRIGERADOR HORIZONTAL 250L 1PTA", 
            "Cantidad" : 1.0, 
            "IdUMedidaOK" : "2", 
            "IdUMedidaBK" : "2", 
            "detail_row" : {
                "FechaReg" : "2023-06-15T08:45:22+07:00", 
                "UsuarioReg" : "JSMITH", 
                "FechaUltMod" : "2023-06-15T08:45:22+07:00", 
                "UsuarioMod" : "JSMITH", 
                "Activo" : "S", 
                "Borrado" : "N"
            }
        }
    ], 
    "cat_prod_serv_archivos" : [
        {
            "DesArchivo" : "Foto del refrigerador", 
            "RutaArchivo" : "https://images.pexels.com/photos/1037989/pexels-photo-1037989.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260", 
            "IdTipoGenArchivoOK" : "8", 
            "IdGenArchivoOK" : "20", 
            "TipoArchivo" : "IMAGEN", 
            "IdTipoGenSeccionOK" : "", 
            "IdGenSeccionOK" : "", 
            "TipoSeccion" : "", 
            "Secuencia" : 1, 
            "Principal" : "S", 
            "detail_row" : {
                "FechaReg" : "2023-06-15T08:45:22+07:00", 
                "UsuarioReg" : "JSMITH", 
                "FechaUltMod" : "2023-06-15T08:45:22+07:00", 
                "UsuarioMod" : "JSMITH", 
                "Activo" : "S", 
                "Borrado" : "N"
            }
        }
    ], 
    "cat_prod_serv_info_adicional" : [
        {
            "IdEtiqueta" : "IDMODELO", 
            "Etiqueta" : "MODELO", 
            "Valor" : "250L 1 PTS", 
            "IdTipoGenSeccionOK" : "11", 
            "IdGenSeccionOK" : "34", 
            "TipoSeccion" : "SECCIÓN PRINCIPAL PRODUCTO SERVICIO", 
            "Secuencia" : 10, 
            "detail_row" : {
                "FechaReg" : "2023-06-15T08:45:22+07:00", 
                "UsuarioReg" : "JSMITH", 
                "FechaUltMod" : "2023-06-15T08:45:22+07:00", 
                "UsuarioMod" : "JSMITH", 
                "Activo" : "S", 
                "Borrado" : "N"
            }
        }, 
        {
            "IdEtiqueta" : "IDMARCA", 
            "Etiqueta" : "MARCA", 
            "Valor" : "WHIRLPOOL", 
            "IdTipoGenSeccionOK" : "11", 
            "IdGenSeccionOK" : "34", 
            "TipoSeccion" : "SECCIÓN PRINCIPAL PRODUCTO SERVICIO", 
            "Secuencia" : 20, 
            "detail_row" : {
                "FechaReg" : "2023-06-15T08:45:22+07:00", 
                "UsuarioReg" : "JSMITH", 
                "FechaUltMod" : "2023-06-15T08:45:22+07:00", 
                "UsuarioMod" : "JSMITH", 
                "Activo" : "S", 
                "Borrado" : "N"
            }
        }, 
        {
            "IdEtiqueta" : "IDDIMENCIONMM", 
            "Etiqueta" : "DIMENCIÓN EN MM", 
            "Valor" : "1500/900/750", 
            "IdTipoGenSeccionOK" : "11", 
            "IdGenSeccionOK" : "34", 
            "TipoSeccion" : "SECCIÓN PRINCIPAL PRODUCTO SERVICIO", 
            "Secuencia" : 30, 
            "detail_row" : {
                "FechaReg" : "2023-06-15T08:45:22+07:00", 
                "UsuarioReg" : "JSMITH", 
                "FechaUltMod" : "2023-06-15T08:45:22+07:00", 
                "UsuarioMod" : "JSMITH", 
                "Activo" : "S", 
                "Borrado" : "N"
            }
        }, 
        {
            "IdEtiqueta" : "IDPESOKG", 
            "Etiqueta" : "PESO EN KG", 
            "Valor" : "120.750", 
            "IdTipoGenSeccionOK" : "11", 
            "IdGenSeccionOK" : "34", 
            "TipoSeccion" : "SECCIÓN PRINCIPAL PRODUCTO SERVICIO", 
            "Secuencia" : 40, 
            "detail_row" : {
                "FechaReg" : "2023-06-15T08:45:22+07:00", 
                "UsuarioReg" : "JSMITH", 
                "FechaUltMod" : "2023-06-15T08:45:22+07:00", 
                "UsuarioMod" : "JSMITH", 
                "Activo" : "S", 
                "Borrado" : "N"
            }
        }
    ], 
    "detail_row" : {
        "FechaReg" : "2023-06-15T08:45:22+07:00", 
        "UsuarioReg" : "JSMITH", 
        "FechaUltMod" : "2023-06-15T08:45:22+07:00", 
        "UsuarioMod" : "JSMITH", 
        "Activo" : "S", 
        "Borrado" : "N"
    }
}


### DELETE fisicamente
DELETE {{api}}/hard/103
### DELETE solo en estatus
DELETE {{api}}/soft/102?keyType=OK
### DELETE Solo en estatus
DELETE {{api}}/soft/101

##PROBANDO EL DE NEGOCIOS ADD
PATCH {{api}}/negocios/add/9004-000000000004
Content-Type: application/json

{
        "detail_row": {
          "Activo": "N",
          "Borrado": "N",
          "detail_row_reg": []
        },
        "IdNegocioOK": "9003-TODOS"
}

##Probando Negocios update
PATCH {{api}}/negocios/update/9004-000000000004
Content-Type: application/json

{
        "detail_row": {
          "Activo": "N",
          "Borrado": "S",
          "detail_row_reg": [
            {
              "FechaReg": "2023-11-14T17:42:25.804Z",
              "UsuarioReg": "TestUser"
            }
          ]
        },
        "IdNegocioOK": "gfdg",
        "_id": "6553b181182ea183b3889de2"
}

##Probando Negocios DELETE
PATCH {{api}}/negocios/delete/9004-000000000004/9003-TODOS

### patch
PATCH {{api}}/9002-000000000002/estatus/aa
Content-Type: application/json
Authorization: Bearer <tu_token_de_autenticación>

{
  "Activo": "M",
  "Borrado": "M",
  "detail_row_reg": []
}